---
version: '3'
services:
  psql:
    image: jutonz/homepage-dev-psql:4
    volumes:
    - "../../:/tmp/code"
    - "../../tmp/psql-dev:/var/lib/postgresql/data"
  redis:
    image: jutonz/homepage-dev-redis:1
  app:
    image: jutonz/homepage-dev-app:13
    volumes:
    - "../../:/root"
    - "/root/apps/client/assets/node_modules"
    ports:
    - 4000:4000
    depends_on:
    - psql
    - redis
    links:
    - psql
    - redis
