---
version: '3'
services:
  psql:
    image: jutonz/homepage-dev-psql:4
    volumes:
    - "../../:/tmp/code"
    - "../../tmp/psql-dev:/var/lib/postgresql/data"
  app:
    image: jutonz/homepage-dev-app:8
    volumes:
    - "../../:/root"
    - "/root/assets/node_modules"
    ports:
    - 4000:4000
    depends_on:
    - psql
    links:
    - psql
