version: '3'
services:
  psql:
    image: jutonz/homepage-dev-psql:1
    volumes:
      - ../../tmp/psql-dev:/var/lib/postgresql/data
  app:
    image: jutonz/homepage-dev-app:1
    command: mix phx.server
    volumes:
      - ../../:/root
    ports:
      - '4000:4000'
    depends_on:
      - psql
    links:
      - psql
