version: '3'
services:
  psql:
    image: jutonz/homepage-dev-psql:3
    volumes:
      - ../../:/tmp/code
      - ../../tmp/psql-dev:/var/lib/postgresql/data
  app:
    image: jutonz/homepage-dev-app:2
    stdin_open: true
    tty: true
    volumes:
      - ../../:/root
    ports:
      - "4000:4000"
    depends_on:
      - psql
    links:
      - psql
