---
web:
  ingress:
    enabled: true
    hosts: ["ci.jutonz.com"]
persistence:
  ## Disable PVC since running on baremetal
  enabled: false
postgresql:
  # Use our own psql instance so we can handle backups
  enabled: false
  # uri: postgres://homepage:homepage@psql:5432/homepage_prod
  # Pass --set "postgresq.uri"="" to helm install to avoid storing secrets here
