---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: ci
spec:
  selector:
    app: web
  ports:
  - name: interface
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: worker-entry
    protocol: TCP
    port: 2222
    targetPort: 2222
