---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: jutonz/homepage-ci-web:1
        name: web
        command: ["/usr/local/bin/concourse"]
        args:
        - web
        - "--basic-auth-username=$(CONCOURSE_BASIC_AUTH_USERNAME)"
        - "--basic-auth-password=#(CONCOURSE_BASIC_AUTH_PASSWORD)"
        - "--session-signing-key=/concourse-keys/web/session_signing_key"
        - "--tsa-host-key=/concourse-keys/web/tsa_host_key"
        - "--tsa-authorized-keys=/concourse-keys/web/authorized_worker_keys"
        - "--external-url=https://ci.jutonz.com"
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo 'DUDEZ'; ls -al /concourse-keys > /etc/message"]
        volumeMounts:
        - name: secret-keys
          mountPath: "/concourse-keys/web"
          readOnly: true
        - name: secret-worker-keys
          mountPath: "/concourse-keys/worker"
          readOnly: true
        imagePullPolicy: Always
        env:
          - name: CONCOURSE_EXTERNAL_URL
            value: ci.jutonz.com
          - name: CONCOURSE_POSTGRES_DATABASE
            value: concourse
          - name: CONCOURSE_POSTGRES_HOST
            value: psql
          - name: CONCOURSE_POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: ci-secrets
                key: PGUSER
          - name: CONCOURSE_POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ci-secrets
                key: PGPASS
          - name: CONCOURSE_BASIC_AUTH_USERNAME
            valueFrom:
              secretKeyRef:
                name: ci-secrets
                key: BASIC_AUTH_USERNAME
          - name: CONCOURSE_BASIC_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ci-secrets
                key: BASIC_AUTH_PASSWORD
      restartPolicy: Always
      volumes:
      - name: secret-keys
        secret:
          secretName: ci-web-tls-keys
          items:
          - key: authorized_worker_keys
            path: authorized_worker_keys
          - key: session_signing_key
            path: session_signing_key
          - key: session_signing_key.pub
            path: session_signing_key.pub
          - key: tsa_host_key
            path: tsa_host_key
          - key: tsa_host_key.pub
            path: tsa_host_key.pub
      - name: secret-worker-keys
        secret:
          secretName: ci-worker-tls-keys
          items:
          - key: tsa_host_key.pub
            path: tsa_host_key.pub
          - key: worker_key
            path: worker_key
          - key: worker_key.pub
            path: worker_key.pub
