version: "2"
services:
  nginx:
    depends_on:
      - app
    image: jutonz/homepage-prod-nginx:2
    links:
      - app
    ports:
      - "4444:80"
  app:
    image: jutonz/homepage-prod-app:3
    environment:
      PGHOST: prod-db.chbuu5wubqy2.us-east-1.rds.amazonaws.com
