version: "2"
services:
  nginx:
    depends_on:
      - app
    image: jutonz/homepage-prod-nginx:3
    links:
      - app
    ports:
      - "4000:80"
  app:
    image: jutonz/homepage-prod-app:15
    depends_on:
      - psql
    environment:
      DATABASE_URL: postgres://docker:docker@psql:5432/homepage_prod
      PGHOST: psql
      PGUSER: docker
      PGPASS: docker
      PORT: "4000"
  psql:
    image: postgres:10.0-alpine
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: homepage_prod
