apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: jutonz/homepage-prod-app:1
        name: app
      restartPolicy: Always
      env:
        - name: PGHOST
          valueFrom:
            secretKeyRef: dbsecrets
            key: PGHOST
        - name: PGPASS
          valueFrom:
            secretKeyRef: dbsecrets
            key: PGPASS
