apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: jutonz/homepage-prod-app:3
        name: app
        env:
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: secret-key-base
                key: SECRET_KEY_BASE
          - name: PGHOST
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: PGHOST
          - name: PGPASS
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: PGPASS
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: PGUSER
      restartPolicy: Always
