apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: homepage
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: k8s-master-home.jutonz.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
