apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: homepage
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: jutonz.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
