apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: homepage
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - jutonz.com
    secretName: jutonz-tls
  rules:
  - host: jutonz.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
