apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: psql
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
      - image: jutonz/homepage-prod-psql:9
        name: psql
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: PGUSER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: PGPASS
          - name: POSTGRES_DB
            value: homepage_prod
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: AWS_SECRET_ACCESS_KEY
      restartPolicy: Always
