apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: psql
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
      - image: postgres:10.0-alpine
        name: psql
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: PGUSER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: PGPASS
          - name: POSTGRES_DB
            value: homepage_prod
      restartPolicy: Always
