apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: psql
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
      - image: jutonz/homepage-prod-psql:2
        name: psql
      restartPolicy: Always
